name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  riscv-tests:
    runs-on: ubuntu-latest
    container: kamiyaowl/riscv-gnu-toolchain-docker

    steps:
    - uses: actions/checkout@v2
    - name: make riscv-tests
      run: git clone https://github.com/riscv/riscv-tests
